# Generated by Django 5.2.11 on 2026-02-27 22:18

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=documents.models.document_upload_to)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('LEASE_AGREEMENT', 'Lease agreement'), ('INVOICE', 'Invoice / receipt'), ('PROPERTY_PHOTO', 'Property photo'), ('MAINTENANCE_PHOTO', 'Maintenance photo / attachment'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['lease', 'invoice', 'property', 'maintenancerequest']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
